name: Build
on: [push, pull_request]
jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Set GOPATH
      # temporary fix (see https://github.com/actions/setup-go/issues/14)
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin/windows_386"
      shell: bash      

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Update build dependencies
      run: make setup

    - name: Check quality code
      run: make verify

    - name: Test
      run: make test

    - name: Build
      run: make build
