name: Release
on:
  push:
    branches: ["master"]
    paths:
      - "VERSION"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Set GOPATH
      # temporary fix (see https://github.com/actions/setup-go/issues/14)
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1       

    - name: Generate releases
      run: make builds

    - name: Prepare
      id: prepare
      run: |
        VERSION=$(cat VERSION)
        echo ::set-output name=version::${VERSION}
      shell: bash

    - name: GitHub Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        draft: true
        files: |
          dist/kw_darwin-amd64
          dist/kw_linux-amd64
          dist/kw_windows-amd64
        name: ${{ steps.prepare.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
